### PR TITLE
Old Code Begone (Removed Goldsrc Support)

### PR DESCRIPTION
**Pull request by Gocnak**
Removed RMF, MAP, and WAD references.
Removed Prefabs Factory & Dialogs as they were only geared towards Goldsrc stuff really
Moved Prefabs folder into the hammer/ folder

### CODE REVIEW

**Comment by SCell555** [comment]
Looks good. I think that CTexture and TEXTUREFORMAT are no longer needed. CTexture was never used for anything, and we don't have any other texture format than tfVMT.

**Comment by Gocnak** [comment]
Yeah good point, I'll remove those too.

**Comment by Gocnak** [comment]
Alright this should be ready for merge, Let me know if there's anything else I missed!

**Comment by SCell555** [comment]
I think that's all. Only other thing I can think of is resource.h, it has quite a few references to Quake 2.

**Pull request merged**
